# bridge.yaml – MCP Bridge (PocketBase ↔ Agent)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-bridge
spec:
  replicas: 1
  selector:
    matchLabels: { app: bridge }
  template:
    metadata: { labels: { app: bridge } }
    spec:
      containers:
      - name: bridge
        image: lupca/tmcp-m-bridge:latest
        env:
        - name: POCKETBASE_URL
          value: "http://pb-service"
        - name: POCKETBASE_USER
          value: "admin@admin.com"
        - name: POCKETBASE_PASSWORD
          value: "123qweasdzxc"
        ports: [{ containerPort: 7999 }]
---
apiVersion: v1
kind: Service
metadata:
  name: bridge-service
spec:
  selector: { app: bridge }
  ports: [{ port: 80, targetPort: 7999 }]
